version: 2
static:
  include:
    - /index.html
    - /berlin/index.html
    - /cottbus/index.html
    - /stuttgart/index.html
    - /community/index.html
    - /projekte/index.html
    - /blog/code-for-berlin-talks/index.html
    - /projekte/pricemap-eu/index.html
    - /spenden.html
discovery:
  disable-cache: true
